import Head from 'next/head';
import Hero from '../sections/Hero';
import ServicesSection from '../sections/Services';
import Solutions from '../sections/Solutions';
import Industries from '../sections/Industries';
import Technologies from '../sections/Technologies';
import CaseStudies from '../sections/CaseStudies';
import CompanyTech from '../sections/CompanyTech';
import Faq from '../sections/Faq';
import GetProposalSection from '../sections/GetProposal';

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<Hero />
				<ServicesSection />
				<Solutions />
				<Industries />
				<Technologies />
				<CaseStudies />
				<CompanyTech />
				<Faq />
				<GetProposalSection />
			</main>
		</>
	)
}
